### ISSUE TITLE
git.add does not allow for specified files to add in another cwd

### ISSUE THREAD

**Issue by mwpowellhtx** [stevelacy/gulp-git#178]
There needs to be better comprehension around the "files" part of the arguments.

My situation:

* I have a repo that is other than the folder from which git.add is invoked, so I need to comprehend either: 1) gulp.src(...) differently, or 2) be able to specify the repo directory, i.e. git.add({ args: ".", cwd: repoDir })

But which does not add the files as expected.

If I pass the full path of the file(s) in question, then Git complains, of course, the file is "outside" the repository.

**Comment by mwpowellhtx** [comment]
Considering the current state of the source, it looks to me like you are assuming that the current ``process.cwd()`` is where the files are. You overwrite the add ``cwd`` during ``flush``, but never did so during the ``write``, where the files are gathered. It would be better to respect the given ``opts.cwd``, or allow for ``options`` passed in that include the specific file names that callers want to add.

This is a bit of a rabbit hole for me. If I must, I will submit a PR, but would this be difficult to correct and publish in the near future?

**Comment by stevelacy** [comment]
The input from git.add should be just the vinyl files with their own cwd's attached. It may be needed to alter the cwd on each vinyl object prior to passing through the write, rather than just getting the cwd from one file in the src which is causing the issue.
opts.cwd is only respected by the git process on the write, not the source, and is quite limiting as is.
I'm wondering if copying the files to the "new" cwd before passing through the `add` would work.

I'll definitely accept a PR, thanks

**Comment by mwpowellhtx** [comment]
@stevelacy If I understand correctly, ``add` in this instance is trying to be *"helpful"*. This isn't how ``git add`` actually runs, which I do not think any proxy should be any more helpful than that. In other words, the end user decides *what*, *where*, *when*, etc, to *create*, *copy*, *move*, etc, into the repository. Then runs ``git add``.

**Comment by stevelacy** [comment]
git.add assumes the file already exists inside the git repo, and passes it farther down to `git add`.
Yes, the user should use copy before git.add
