### ISSUE TITLE
commit() will commit also unstaged files

### ISSUE THREAD

**Issue by dloreto** [stevelacy/gulp-git#186]
Running the commit function will commit bot staged and unstaged files. I would expect to commit only staged files.

I manually staged some files in a repository then i run this code snippet:
```
gulp.src('./*').pipe(
   git.commit("My message")
)
```

**Comment by stevelacy** [comment]
This is by design: https://github.com/stevelacy/gulp-git/blob/master/lib/commit.js#L79

You can submit a PR to add an option for it.

**Comment by gilly3** [comment]
That line seems to apply specifically when `--amend` is specified, which doesn't apply to me, but I was still getting unstaged files added to the commit.  I believe the real culprit is [commit.js, Line L90](https://github.com/stevelacy/gulp-git/blob/master/lib/commit.js#L90), and it can be suppressed via `disableAppendPaths: true`.
